### ISSUE TITLE
"Resilience" should be "Socio-economic capacity" in the PHL

### ISSUE THREAD

**Issue by adrivsh** [worldbank-climate-group/resilience-indicator-tool#1]
As per attached input_info.csv, the rendering of `resilience` on the maps and output panel, in the case of the PHL, should be **Socioeconomic capacity**

[inputs_info.zip](https://github.com/worldbank-climate-group/res-ind-tool-country-level/files/324201/inputs_info.zip)

**Comment by bjohare** [comment]
zipfile is empty.. can you send it via email?

**Comment by adrivsh** [comment]
Will do

Can you just change resilience to socioeconomic capacity in input info.csv
for the the phl meanwhile?

**Comment by bjohare** [comment]
Done.

**Comment by adrivsh** [comment]
Seems to have changed for world also. no big deal but keeping this opened for futrue reference
