### ISSUE TITLE
Filter out duplicate ISO codes from map data

### ISSUE THREAD

**Issue by bjohare** [worldbank-climate-group/resilience-indicator-tool#15]
Some countries, eg USA have multiple territories. Should just use model data for single territory. Perhaps add config parameter to specify which should be filtered out..

**Comment by adrivsh** [comment]
The way i would do this is by making the topojson map a visualization tool only, like the scatter plot.

There would be 3 elements:
- a table
- a map
- a plot

There would be one table that has one line per country and columns for inputs and outputs.
That table has only one line per country, irrespective of how the countries look like in a map. This is the table that is given to and taken back from the python function.

Separately, there is a process that looks at the map, look at the attributes in the features of the maps, and colors the map. It is this process that can connect one line in the data to two islands in the map.

A similar process connects one line in the data to one single bubble in the scatter plot. This is more straightforward.

I think the advantage of this process is to keep thing well sorted. The data table has the format the data table needs for the model. The map contains data on color, and maybe one value, per feature, and that is it.
The map doe snot understand how the python model works.
The python model does not understand how the map works.
And a third part of the code just understands how to link model outputs to the map.

Does that make sense?

**Comment by bjohare** [comment]
Fixed.

**Comment by adrivsh** [comment]
guess it is fixed!
