### ISSUE TITLE
[CLOSED] Filter out duplicate ISO codes from map data

### ISSUE THREAD

**Issue by bjohare** [worldbank-climate-group/resilience-indicator-tool#16]
<a href="https://github.com/bjohare"><img src="https://avatars.githubusercontent.com/u/3308136?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bjohare](https://github.com/bjohare)**
_Monday Jun 06, 2016 at 08:43 GMT_
_Originally opened as https://github.com/worldbank-climate-group/resilience-indicator-tool-old/issues/15_

---

Some countries, eg USA have multiple territories. Should just use model data for single territory. Perhaps add config parameter to specify which should be filtered out..

**Comment by bjohare** [comment]
<a href="https://github.com/adrivsh"><img src="https://avatars.githubusercontent.com/u/10272606?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [adrivsh](https://github.com/adrivsh)**
_Monday Jun 06, 2016 at 13:23 GMT_

---

The way i would do this is by making the topojson map a visualization tool only, like the scatter plot.

There would be 3 elements:
- a table
- a map
- a plot

There would be one table that has one line per country and columns for inputs and outputs.
That table has only one line per country, irrespective of how the countries look like in a map. This is the table that is given to and taken back from the python function.

Separately, there is a process that looks at the map, look at the attributes in the features of the maps, and colors the map. It is this process that can connect one line in the data to two islands in the map.

A similar process connects one line in the data to one single bubble in the scatter plot. This is more straightforward.

I think the advantage of this process is to keep thing well sorted. The data table has the format the data table needs for the model. The map contains data on color, and maybe one value, per feature, and that is it.
The map doe snot understand how the python model works.
The python model does not understand how the map works.
And a third part of the code just understands how to link model outputs to the map.

Does that make sense?

**Comment by bjohare** [comment]
<a href="https://github.com/bjohare"><img src="https://avatars.githubusercontent.com/u/3308136?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bjohare](https://github.com/bjohare)**
_Thursday Jun 16, 2016 at 13:01 GMT_

---

Fixed.

**Comment by bjohare** [comment]
<a href="https://github.com/adrivsh"><img src="https://avatars.githubusercontent.com/u/10272606?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [adrivsh](https://github.com/adrivsh)**
_Thursday Jun 16, 2016 at 13:29 GMT_

---

guess it is fixed!

**Comment by adrivsh** [comment]
still see Guantanamo Bay... so, is it fixed?

**Comment by bjohare** [comment]
Fixed now.
