### ISSUE TITLE
Remove requirement to clear cache

### ISSUE THREAD

**Issue by bjohare** [worldbank-climate-group/resilience-indicator-tool#17]
<a href="https://github.com/adrivsh"><img src="https://avatars.githubusercontent.com/u/10272606?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [adrivsh](https://github.com/adrivsh)**
_Wednesday Jun 08, 2016 at 18:00 GMT_
_Originally opened as https://github.com/worldbank-climate-group/resilience-indicator-tool-old/issues/16_

---

i guess one can set expiry date for cache ?

**Comment by bjohare** [comment]
<a href="https://github.com/adrivsh"><img src="https://avatars.githubusercontent.com/u/10272606?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [adrivsh](https://github.com/adrivsh)**
_Thursday Jun 16, 2016 at 13:31 GMT_

---

Current situation is that hitting F5 actually reloads the page entirely. 

But just going to  wb.geoweb.io from another page (or from that same page for that matter) does not actually reloads the page from the server.

**Comment by bjohare** [comment]
Do we still need this.. am reluctant to disable caching as it will increase page load times?

**Comment by adrivsh** [comment]
flagging with a milestone this is not Brian job (label would be better but cant add label)

The point is to let the client browser know when there is a new version in the server, in that case the client browser understands its cache is expireded and recaches

**Comment by adrivsh** [comment]
actually this is already fixed, somehow.
