### ISSUE TITLE
Manage extended distributions (hazard protection in world)

### ISSUE THREAD

**Issue by bjohare** [worldbank-climate-group/resilience-indicator-tool#20]
I need to think this through, i see two solutions:
- provide a max bound to crop the distribution in input_info
- use 1/protection instead of protection as input

**Comment by adrivsh** [comment]
Not fixed, i get a flat distro for hazard in World 

![delme](https://cloud.githubusercontent.com/assets/10272606/17629656/6c06af66-6089-11e6-937f-b8afe5979979.png)

for reference, this is my old implementation

![untitled](https://cloud.githubusercontent.com/assets/10272606/17629698/a34f546e-6089-11e6-9ede-793b3d0ee001.png)

**Comment by bjohare** [comment]
Duplicate of #43
