### ISSUE TITLE
Have bins instead of continuous colormaps in maps

### ISSUE THREAD

**Issue by bjohare** [worldbank-climate-group/resilience-indicator-tool#25]
Look here for inspiration: https://github.com/adrivsh/world-map-plots/blob/master/draw_maps.ipynb

**Comment by bjohare** [comment]
Looks ok but happy to discuss. Maybe resilience could use a more divergent color scale?

**Comment by adrivsh** [comment]
It's OK

for reference for the report i use RdPu, YlGnBu and YlOrRd_r  (REVERTED, dark color is low resi) for welfare, assets, resi respectively

if you want to spend 2 minutes updating to these that would be even better. otherwise feel free to close

(names from http://colorbrewer2.org/ of course)
