### ISSUE TITLE
Minimap selector maps should be of their corresponding color

### ISSUE THREAD

**Issue by adrivsh** [worldbank-climate-group/resilience-indicator-tool#35]
Now, they are gray:

![untitled](https://cloud.githubusercontent.com/assets/10272606/17629926/f6ede490-608a-11e6-9c9d-02f2c2d2c569.png)

Instead, should use the corresponding color (asset blue, welf purple, resi red)
![delme](https://cloud.githubusercontent.com/assets/10272606/17629940/13f5bb08-608b-11e6-8f56-c8e088e0e050.png)

(slidghtly related to https://github.com/worldbank-climate-group/resilience-indicator-tool/issues/25 )

**Comment by bjohare** [comment]
Have just added a block color to each of the maps since we're not joining model data to the map data anymore.
