### ISSUE TITLE
use expanded dataset for world version

### ISSUE THREAD

**Issue by adrivsh** [worldbank-climate-group/resilience-indicator-tool#39]
This should just consist on using this dataframe instead fo the old one:

[df.zip](https://github.com/worldbank-climate-group/resilience-indicator-tool/files/415806/df.zip)

leading to more countries with all data, for instance:
![map_of_resilience](https://cloud.githubusercontent.com/assets/10272606/17630433/3f6187f2-608d-11e6-86ef-d2b172e5ac83.png)

**Comment by bjohare** [comment]
df.csv should have column named `id` containing 3 letter ISO code matching `ISO_Codes` field in WB_CountryPolys.shp. Joining manually using QGIS for now but Resilience Tool with not work out of the box without this in future.

**Comment by adrivsh** [comment]
Sorry if i ever do that again use this table to convert names to iso 
https://github.com/adrivsh/country_names/blob/master/iso3_to_wb_name.csv
