### ISSUE TITLE
Enhance tooltip in the map pane

### ISSUE THREAD

**Issue by bjohare** [worldbank-climate-group/resilience-indicator-tool#4]
<a href="https://github.com/adrivsh"><img src="https://avatars.githubusercontent.com/u/10272606?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [adrivsh](https://github.com/adrivsh)**
_Tuesday May 31, 2016 at 00:43 GMT_
_Originally opened as https://github.com/worldbank-climate-group/resilience-indicator-tool-old/issues/3_

---
- remove the 3 letter iso code:
  "Brazil", not "Brazil (BRA)"
- Do not repeat the current output in the tooltip
- render numbers as .1%  (percentage with 1 digit after the coma)
- keep it ative for current country ?

**Comment by bjohare** [comment]
<a href="https://github.com/adrivsh"><img src="https://avatars.githubusercontent.com/u/10272606?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [adrivsh](https://github.com/adrivsh)**
_Thursday Jun 16, 2016 at 13:28 GMT_

---

Do not repeat the current output in the tooltip

render numbers as .1% (percentage with 1 digit after the coma)

keep it ative for current country ? (clicking in a country/province locks the "tooltip")

**Comment by bjohare** [comment]
Done.

**Comment by adrivsh** [comment]
Still unit issue, for instance resiiece is diplayed at .7%, should be 70%, but that is it's own bug now
