### ISSUE TITLE
Syncronize mouse over events across panels [WONTFIX]

### ISSUE THREAD

**Issue by bjohare** [worldbank-climate-group/resilience-indicator-tool#6]
<a href="https://github.com/adrivsh"><img src="https://avatars.githubusercontent.com/u/10272606?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [adrivsh](https://github.com/adrivsh)**
_Tuesday May 31, 2016 at 00:46 GMT_
_Originally opened as https://github.com/worldbank-climate-group/resilience-indicator-tool-old/issues/5_

---

Moving mouse over country in map should highlight bubbles in input and output panels

Moving mouse in bubble panels should highlight countries in the map too

**Comment by adrivsh** [comment]
this is a bit silly, i'm gonna close it
